### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by albertopasqualetto** [samueleisalinuxuser/pixel-customizations#1]
The name of the action "Backgroung image and varius Icons" should be "Background image and various Icons"

**Comment by samueleisalinuxuser** [comment]
thanks for the correction, I'm sorry for the mistakes

**Comment by albertopasqualetto** [comment]
In panel settings:
"If you right click the panel you can notice there are two settings main tools to stylize it:" sound be without "settings".

**Comment by albertopasqualetto** [comment]
"After having done that, open the second menu, it will appear four sections:" -> "... and four sections will appear:"

And there is again "backgroung"

**Comment by albertopasqualetto** [comment]
In themes and appearance there is "onestly" instead of "honestly" and also the title should be "appearance".
Also check in the other pages for typos in the place of "background".

**Comment by samueleisalinuxuser** [comment]
I'm correcting my grammatical horrors, thanks for your help. However, I'm thinking to rewrite some parts I believe sounds bad

**Comment by samueleisalinuxuser** [comment]
If you find other horrors, please alert me

**Comment by albertopasqualetto** [comment]
I read everything quickly and the other parts seem good. Maybe some parts
could sound better if you rewrite them. Good job anyway.👍🏻

Il Mar 9 Giu 2020, 22:59 Samuele Cistaro <notifications@github.com> ha
scritto:

**Comment by samueleisalinuxuser** [comment]
Thanks
